### ISSUE TITLE
Old Versions

### ISSUE THREAD

**Issue by ImAlwaysInFaMouS** [TheRemote/Legendary-Bedrock-Container#11]
So I'ev managed to get a docker container of the latest release bedrock loaded and working(on volume 1). Since then I've been looking into addons for the servers, so i wanted to run a 1.17.0 server, but when i run:

"sudo docker run -it -v yourvolumename2:/minecraft -e Version=1.17.0 -p 19199:19199/udp -p 19198:19198 --restart unless-stopped 05jchambers/legendary-bedrock-container:latest"

It still loads the latest....

>pi@raspberrypi:~ $ sudo docker run -it -v yourvolumename2:/minecraft -e Version=1.17.0 -p 19199:19199/udp -p 19198:19198 --restart unless-stopped 05jchambers/legendary-bedrock-container:latest
Minecraft Bedrock Server Docker script by James A. Chambers
Latest version always at https://github.com/TheRemote/Legendary-Bedrock-Container
Don't forget to set up port forwarding on your router!  The default port is 19132
Ports used - IPV4: 19132 - IPV6: 19133
Taking ownership of all server files/folders in /minecraft...
Complete
No daily restart scheduled
Backing up server (to minecraftbe/backups folder)
Backing up server (multiple cores) to minecraftbe/backups folder
worlds/
worlds/Bedrock level/
worlds/Bedrock level/level.dat_old
worlds/Bedrock level/levelname.txt
worlds/Bedrock level/level.dat
worlds/Bedrock level/db/
worlds/Bedrock level/db/CURRENT
worlds/Bedrock level/db/MANIFEST-000014
worlds/Bedrock level/db/000015.log
Checking for the latest version of Minecraft Bedrock server ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  318k    0  318k    0     0   282k      0 --:--:--  0:00:01 --:--:--  282k
Latest version online is bedrock-server-1.19.51.01.zip
Override version, using version specified: 1.17.0 as bedrock-server-1.17.0.zip
Current install is: bedrock-server-1.17.0.zip
Requested version bedrock-server-1.17.0.zip is already installed
Starting Minecraft server...
[2022-12-25 11:59:07] NO LOG FILE! - setting up server logging...
[2022-12-25 11:59:07] [2022-12-25 11:59:07:087 INFO] Starting Server
[2022-12-25 11:59:07] [2022-12-25 11:59:07:093 INFO] Version 1.19.51.01
[2022-12-25 11:59:07] [2022-12-25 11:59:07:093 INFO] Session ID 7283969f-2d29-44fe-a70c-bcc69ed55e39
[2022-12-25 11:59:07] [2022-12-25 11:59:07:138 INFO] Level Name: Bedrock level
[2022-12-25 11:59:07] [2022-12-25 11:59:07:181 INFO] Game mode: 0 Survival
[2022-12-25 11:59:07] [2022-12-25 11:59:07:182 INFO] Difficulty: 1 EASY
[2022-12-25 11:59:07] [2022-12-25 11:59:07:591 INFO] Content logging enabled. Writing log to: ContentLog__Sunday__2022_December_25__11_59_07
[2022-12-25 11:59:07] [2022-12-25 11:59:07:615 INFO] opening worlds/Bedrock level/db

**Comment by TheRemote** [comment]
Hello,

I think I can help!  So there's no such thing as Minecraft server version 1.17.0.  You can take whatever version you want to get and put it in Microsoft's web site like this:

https://minecraft.azureedge.net/bin-win/bedrock-server-1.17.0.zip

We can see there's no file found for that on Microsoft's servers.  If you look at the current one on their download page now the current version is:

https://minecraft.azureedge.net/bin-win/bedrock-server-1.19.51.01.zip

You are going to need to know the exact version that you want to run.  1.17.0 isn't good enough because Bedrock doesn't work like Java Minecraft.  It's going to be some really weird other version like 1.17.50.2 or who knows.  I'm not even sure how you'd find the old ones unless you were specifically targeting an exact version.

Like for example we are now on Java Minecraft 1.19.3 yet the Bedrock version for that is 1.19.51.01.  Obviously that looks nothing like 1.19.3 and if you put -e Version=1.19.3 you would get the same error.  There's basically nothing for it to download off Microsoft's servers so it's falling back to the old version.

If you know the exact right dedicated server version to download in there (and it exists on Microsoft's servers when you try it manually) then it will work!

**Comment by ImAlwaysInFaMouS** [comment]
Ok thanks, I'll try doing some googleing for bedrock server version and hopfully i get lucky, Great container BTW!!

**Comment by TheRemote** [comment]
No problem at all!  The client may be able to help if you have a specific older client you're targeting.

They don't always match one to one but it's definitely a start and sometimes (especially upon the first release) they'll be in sync.  Other times the client will be something like 1.17.50.21 and the server might be 1.17.50.5 if that makes sense.

I would definitely start with the exact client one if you have it.  It should be possible to get that to pop up within the game menus itself and get the exact version (or even right click on the Minecraft .exe and go to the "Properties" tab and look what they filled out for Version).

Best of luck, hopefully someone has compiled information like this somewhere (or even if you found an old screenshot happening to show one from that era)!

**Comment by ImAlwaysInFaMouS** [comment]
So i found this: https://minecraft.fandom.com/wiki/Bedrock_Dedicated_Server

It has version list, i tried the link and changed it for "1.7.0.13" , and it downloaded, so ill give it ago in docker

**Comment by TheRemote** [comment]
Bingo!  That is perfect and a pretty amazing / comprehensive list.

Now the only question is to get a version of 1.17 that is compatible enough with the client that the client won't complain when connecting.  With this list though it shouldn't be too hard to move through the different versions though until you find one close enough for the client.

Thanks for sharing that list by the way, I had not seen it before!

**Comment by ImAlwaysInFaMouS** [comment]
Glad i could help :) Thank you again
