### ISSUE TITLE
no automatic update

### ISSUE THREAD

**Issue by pL4uN3r** [TheRemote/Legendary-Bedrock-Container#12]
Hallo
i can not connect to server because of client update.
the log says: "Unable to connect to update website (internet connection may be down).  Skipping update ..."

when i start a new container...
`Checking for the latest version of Minecraft Bedrock server ...
Unable to connect to update website (internet connection may be down).  Skipping update ...
Starting Minecraft server...
[2023-02-26 05:31:18] Error: file is not found (check BOX64_PATH)
Minecraft Bedrock Server Docker script by James A. Chambers
Latest version always at https://github.com/TheRemote/Legendary-Bedrock-Container
Don't forget to set up port forwarding on your router!  The default port is 19132
Ports used - IPV4: 19132 - IPV6: 19133
Taking ownership of all server files/folders in /minecraft...
Complete
Checking for the latest version of Minecraft Bedrock server ...`
and so on

**Comment by TheRemote** [comment]
This is a DNS issue that occurs when you try to run Docker on an old Linux distro basically.  I've never seen this not be that.

If I were to guess you are probably running Ubuntu 20.04 or something that is basically obsolete.  Can you share your:

```
uname -a
cat /etc/os-release
```

The way to fix this is to upgrade your Linux distribution to the latest version basically.  How you do this will depend on which one it is though.  Hopefully that helps!

**Comment by pL4uN3r** [comment]
Docker runs on a RaspberryPi4 (i think it was "pi OS x64 lite")... maybe one or two month old

`Linux dockerpi 5.15.89-v8+ #1620 SMP PREEMPT Wed Jan 18 12:26:08 GMT 2023 aarch64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

**Comment by TheRemote** [comment]
Version looks fantastic.  That's the first time I've really seen a broken Docker DNS config on a modern operating system.

So basically what is happening here is that your server can't connect to minecraft.net.  That's what this message means:

`Unable to connect to update website (internet connection may be down).  Skipping update ...`

This is basically step 1.  Since you've never been able to successfully download the server before it will just fail.  Normally if you had successfully ran it once and you lost connectivity it would just run the version you currently have.  Since it can't connect to minecraft.net though you basically don't have a server installed at all.

What happens when you try this command:

`docker run --rm -it alpine ping www.minecraft.net`

Can this docker installation even ping?  It shouldn't be able to if the problem is what I think it is.

Are you also running a Pi-Hole on this?  You might have dnsmasq installed/configured which can screw things up.  Check out this post here: https://discourse.pi-hole.net/t/dns-service-not-running-on-raspberry-pi-4b/52195/7

Here's another one: https://www.reddit.com/r/pihole/comments/rvju0t/pi_hole_in_a_docker_dns_service_not_running_on/

My guess is that you have to be doing something like this and be running something else on there.  If you're using DNSMasq for something you probably need to do some additional configuration so that you can successfully ping / resolve DNS names here.

Hopefully that helps!

**Comment by pL4uN3r** [comment]
I solved it. Your right, i think it was a DNS problem too... 
Yes i run PiHole, even after i throw it out of my "system" it wouldnt work.
I put in the Docker Container for the MCserver > network > DNS > 8.8.8.8
After this the update works.

I read your last comment after all, so thanks for your help so far.

**Comment by TheRemote** [comment]
Thanks for confirming, I'm so glad we were on the right track as I was a little stumped when you said you weren't running an older version of Linux.  That has happened literally dozens of times and this was the first that the answer was "no".

It definitely makes sense though after investigating.  Thanks so much for posting your resolution.  I'm sure this will help others as many people who have a Raspberry Pi will be running a Pi Hole so there's definitely others out there with this configuration that will run into this.

Enjoy and take care!
