### ISSUE TITLE
Container fails to start - Portainer on a pi4

### ISSUE THREAD

**Issue by nkm8** [TheRemote/Legendary-Bedrock-Container#4]
Relevant section of the logs:
```
Starting Minecraft server...

Must be connected to a terminal.
```

Related: https://superuser.com/questions/1508418/must-be-connected-to-a-terminal-in-screen

I attempted to debug this issue, but I hit a roadblock trying to build an arm64v8 image manually. I can also confirm that changing the base image entrypoint to `sleep 999` and using an interactive terminal, I am able to manually execute `/scripts/start.sh`

I am a bit murky on the various flags for the `screen` command, but something about my specific configuration is choking.

**Comment by TheRemote** [comment]
Hey Nick,

What are the files in the "logs" folder showing?  Those are the screen output logs basically.  

Are you using the docker -it flags when running it?  That controls terminal behavior and would explain it for sure.

An easier way to jump into the container is to override the entrypoint like this:

`docker run -it -v minecraftbe:/minecraft -p 19132:19132/udp -p 19132:19132 --entrypoint /bin/bash 05jchambers/legendary-bedrock-container:latest`

This should just take you right to the command prompt where you can cd to the /minecraft named Docker volume mountpoint.  This is what I do when testing issues like this.  

An interactive terminal is always required for it but you don't have to attach to it.  You can change the docker line to docker run -itd and it will stay in the background unless you specifically attach to it.  Even the docker-compose.yml template for this specifies the interactive terminal flags since they're needed for screen (but you don't have to attach).

To understand why an interactive terminal is used (whether you want one or not) it is because Bedrock has absolutely 0 logging capabilities.  It doesn't log anything.  The only reason this has logs at all is because it streams it through the "screen" application and it is the screen application that has those capabilities.

Do you actually have an interactive terminal or is your command line modified from the examples?

**Comment by nkm8** [comment]
@TheRemote Thank you very much for the detailed response! Based on your comments, I was able to resolve the issue by adding these 2 lines to my docker-compose file: https://github.com/TheRemote/Legendary-Bedrock-Container/blob/e4d8d61ec88d5d54bd65f99120a7ebe6d49c3b49/docker-compose.yml#L18-L19

I completely missed these when I was configuring my 'stack' in Portainer. After this change, the server works - albeit a bit slow. Specs:
pi4 8 GB
SSD

I am seeing 3-4 minutes to load the server from a client, but after that, performance is ok.

**Comment by TheRemote** [comment]
Hey nkm8,

Glad to hear it!  It's definitely a bit slow right now.  I'm experimenting with the box64 emulator right now for increased speed particularly on aarch64 which we've had some success with on the non-containerized version (but it's not as easy to implement as QEMU was).

I'm glad you got it working!  Stay tuned for future performance improvements for sure as I am going to investigate just having the Docker container manually build a dynamic executable for box64 that will work on there.

Take care!

**Comment by nkm8** [comment]
I can't wait to see the updates - thanks for the details and keep up the great work! 💯
