### ISSUE TITLE
[Q] Question about permissions / changing user

### ISSUE THREAD

**Issue by vp-en** [TheRemote/Legendary-Bedrock-Container#7]
Hello, and thanks for making such a great docker image. It works wonderful.

Is there any to change the user from `root` to something else? 
In some docker images you can set it using environment tags, like 
`-e PUID=1000` `-e PGID=1000` and `-e UMASK=002`

But it doesn't seem to work on this image. So is there any way to change it another user, instead of `root`? Honestly don't like having everything "locked" behind sudo or using my root user to edit files

**Comment by TheRemote** [comment]
It's full of quirks to try and use non-root users.  Look at these:

```
Add a non-root user to a container
Many Docker images use root as the default user, but there are cases where you may prefer to use a non-root user instead. If you do so, there are some quirks with local filesystem (bind) mounts that you should know about. Specifically:

Docker Desktop for Mac: Inside the container, any mounted files/folders will act as if they are owned by the container user you specify. Locally, all filesystem operations will use the permissions of your local user instead.

Docker Desktop for Windows: Inside the container, any mounted files/folders will appear as if they are owned by root but the user you specify will still be able to read/write them and all files will be executable. Locally, all filesystem operations will use the permissions of your local user instead. This is because there is fundamentally no way to directly map Windows-style file permissions to Linux.

Docker CE/EE on Linux: Inside the container, any mounted files/folders will have the exact same permissions as outside the container - including the owner user ID (UID) and group ID (GID). Because of this, your container user will either need to have the same UID or be in a group with the same GID. The actual name of the user / group does not matter. The first user on a machine typically gets a UID of 1000, so most containers use this as the ID of the user to try to avoid this problem.

```

That's a lot of nasty, nasty quirks.  Now what is the benefit?  The Bedrock server has never been breached.  It doesn't matter if they were running the server as root with maximum permissions to everything.  It's never happened.  To anyone.

So what would happen if you were the first person in history to get breached on the Bedrock server?  The most badass hacker in the world has targeted you and has stack smashed the C++ executable.  Now what?  Also nothing.  The container isn't real.  It only exists in memory.  If they obtained root access to it they would be able to do exactly nothing.  Any changes they make in the container would be 100% lost the second it restarts.

The only thing they could do is change files in your Docker volume.  That's the only thing that persists.  They'd have to be among the smartest hackers ever to even realize this and figure out which endpoint mapping is real.  Again, literally has never happened to anyone ever.

In fact what your proposing is actually a security issue.  You want to be able to edit the Docker volume contents with a regular user.  Now what would happen if that regular user got hacked and it had permissions on Linux (because it needs to, that's a quirk I just posted above)?  Well because of the storage quirks and having to give that person actual real permissions on the host machine you are actually at far greater risk:

`Inside the container, any mounted files/folders will have the exact same permissions as outside the container - including the owner user ID (UID) and group ID (GID). `

Whoa there, not a chance.  That literally defeats the purpose of using Docker.  It's the worst of the standalone version AND the Docker version put together.  You should use my standalone script to be able to do this securely using a user you have set up only to run the Minecraft server that has no sudo rights or access/rights to anything else.  That version if the script is available here:  https://github.com/TheRemote/MinecraftBedrockServer

That one works exactly how you are wanting to.  That's because it's not a container.  Containers don't need a non-root user and there are serious implications for doing this that vary depending on the platform (especially with file permissions).  I guarantee that none of the people using this understand the implications of it unless they have read the Docker documentation like I pasted above.

Have you added your host computer's user to your Docker group?  You shouldn't need root permissions to do hardly anything with it.  sudo adduser james docker followed by a reboot will remove sudo as a requirement from doing any of the Docker commands.  This is how you want to set up Docker.  You may need root permissions to edit the Docker volume contents still.  That is for security purposes and won't be changed.

**Comment by vp-en** [comment]
Thanks for the thorough answer!

**Comment by TheRemote** [comment]
No problem at all, take care, let me know if I can help in any way!
