### ISSUE TITLE
IPV4 port is changing after startup

### ISSUE THREAD

**Issue by shruuub** [TheRemote/Legendary-Bedrock-Container#8]
Hey there, I hope its okay to ask here too. Thanks for the great work! However, for whatever reason the port gets changed (I use the docker compose in the repo).
```
[2022-09-11 08:07:17] [2022-09-11 08:07:17:890 INFO] IPv4 supported, port: 19132
[2022-09-11 08:07:17] [2022-09-11 08:07:17:890 INFO] IPv6 not supported
[2022-09-11 08:07:17] [2022-09-11 08:07:17:558 INFO] Server started.                                                                                                             [2022-09-11 08:07:18] [2022-09-11 08:07:18:614 INFO] ================ TELEMETRY MESSAGE ===================
[2022-09-11 08:07:18] [2022-09-11 08:07:18:614 INFO] Server Telemetry is currently not enabled.                                                                                  [2022-09-11 08:07:18] [2022-09-11 08:07:18:615 INFO] Enabling this telemetry helps us improve the game.                                                                          [2022-09-11 08:07:18] [2022-09-11 08:07:18:615 INFO]
[2022-09-11 08:07:18] [2022-09-11 08:07:18:615 INFO] To enable this feature, add the line 'emit-server-telemetry=true'
[2022-09-11 08:07:18] [2022-09-11 08:07:18:616 INFO] to the server.properties file in the handheld/src-server directory
[2022-09-11 08:07:18] [2022-09-11 08:07:18:616 INFO] ======================================================
[2022-09-11 08:07:18] [2022-09-11 08:07:18:653 INFO] IPv4 supported, port: 36462
[2022-09-11 08:07:18] [2022-09-11 08:07:18:653 INFO] IPv6 not supported
```
This are basically the logs, and the ipv4 port changes every time (After every restart). Idk why ipv6 isnt working too but that isnt my main problem rn.

**Comment by TheRemote** [comment]
Hey shruuub,

That is a 3-4 year old bug with the Bedrock ports.  It will always do this basically.  The second set of ports will be random.  You don't have IPV6 enabled on your Docker instance but if you did there would be a second random port for IPV6.

This is a bug in all Bedrock servers and is in the Bedrock server itself.  See the following here (this is a very, very old bug, maybe the oldest one I know of):
https://www.reddit.com/r/MCPE/comments/icjkiw/minecraft_dedicated_bedrock_server_showing/
https://bugs.mojang.com/browse/BDS-1094?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true
https://bugs.mojang.com/browse/BDS-3989

I really doubt they will ever fix this bug.  It also doesn't do anything.  That port won't work if you try to use it and it does nothing.  It's purely a visual artifact and you can safely ignore it.  Hopefully that helps!

**Comment by shruuub** [comment]
Alright, I see! However, the connection isnt working still. Is there anything else to test other than nmap to see if the port is open? Since nmap only returns open | filtered as usual

**Comment by TheRemote** [comment]
Is this running on a free VM like Oracle?  Is it running on a Hyper-V VM?  It's actually incredibly common.

It's most likely your VM's configuration needs the correct ports open and security groups assigned.  It's purely configuration on your OS and VM though to open these up.  There's nothing else that needs to be done basically.  If your ports were open you'd be able to connect at this point.

Can you tell me which provider / platform you are using?  I've seen them all.  It just needs to be configured and I can link you to other people who figured out how to configure your platform if you let me know what it is here!

**Comment by shruuub** [comment]
It is in fact an oracle cloud vm. I used ufw allow and allowed all udp traffic in the oracle firewall. 

Might need to manually open that specifc port, will look into that later.

**Comment by TheRemote** [comment]
Indeed.  The Oracle VM is the absolute worst VM in the entire world to configure.  There's several steps.  Everyone who has Oracle goes through this and there have been many.

Check out these threads here:

https://jamesachambers.com/official-minecraft-bedrock-dedicated-server-on-raspberry-pi/comment-page-8/#comment-13946
https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/comment-page-53/#comment-13936
https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/comment-page-49/#comment-13377

Here is one that is for this exact container:

https://jamesachambers.com/legendary-minecraft-bedrock-container/comment-page-2/#comment-13706

```
Just in case it isn’t clear to anyone, you have to set the ingress ports (TCP/UDP) in the Virtual Cloud Network (VCN) security list [as described in the oracle blog] *and* set the ingress ports in a Network Security Group assigned to your instance.
I stuck with a non-standard port number based on others experience, but if you do the above, it might still work for 19132 (but I haven’t tested it).

Oracle do seem to give you a pretty decent VM for free, so it’s definitely worth considering! They also have free instances in a lot of places around the world – this was one of my reasons for moving from google cloud where the free instances are US only – I could have a UK instance on Oracle.
```

Do not feel bad for not seeing these (that isn't what I'm saying).  They are scattered all over.  It is 100% your platform though.  The fix is exactly the same no matter how you are running the server.  It's pure Oracle VM configuration nonsense basically (that no other providers require that I've ever seen).

I didn't see an issue for the container regarding this at all so I'm happy to link and document this.  We've even considered adding documentation specifically for Oracle because so many people try to follow that free Minecraft server tutorial (which doesn't have the steps necessary for it to work, I know exactly which tutorial is it people are following as they've linked me before).

**Comment by shruuub** [comment]
Yup. The conf is really making me wanting to switch sometimes, but having this much ram (especially for minecraft) is just great. Thanks for all the advice :)

**Comment by TheRemote** [comment]
No problem at all!  Thanks for giving me an opportunity to write this issue up for the container.  Let me know if you run into anything stranger but I think you're all set to get over the "hump" for the initial configuration.  

I noted in one of my other replies I linked to that I haven't ever heard of anyone getting the Oracle configuration right on the first try.  That is still true for sure.  I wouldn't have got it on the first try because all of my other VM providers I've used don't really have any equivalent options to some of the security and ingress groups that Oracle uses.

Take care and enjoy, let me know if I can help further for sure!

**Comment by shruuub** [comment]
uhm, I just wondered, is the network security group necessary? because I have forwarded ports without one, and I dont have one right now.

**Comment by TheRemote** [comment]
Supposedly.  I don't use Oracle and never have.  My understanding is that you need you need to create a network security group and attach it to your instance.  

Yes, opening the ports should be enough.  That is a one click operation on Amazon.  If you can't connect still it isn't.  You're right.  It's just opening ports.  What it will take for Oracle to do that I'm not completely sure but others said you need all of it to be able to even connect.
